import { supabaseAdmin } from './supabase/admin';
import { sendOutbidAlert } from './resend';

export interface DispatchOutbidAlertsParams {
  paymentId: string;
  promotedProjectId: string;
  newRank: number;
  amountMinor: number;
}

interface AlertPreferences {
  emailAlerts?: boolean;
  browserAlerts?: boolean;
  instantKingAlert?: boolean;
}

/**
 * Dispatches transactional outbid/demotion alerts when a payment succeeds.
 * Queries board_events to identify affected projects and their owners.
 * Completely non-blocking and fail-safe.
 */
export async function dispatchOutbidAlerts(params: DispatchOutbidAlertsParams): Promise<void> {
  try {
    const { paymentId, promotedProjectId, amountMinor } = params;
    if (!paymentId) return;

    // 1. Fetch the promoted project details
    const { data: promotedProject } = await supabaseAdmin
      .from('projects')
      .select('id, title, handle, user_id')
      .eq('id', promotedProjectId)
      .maybeSingle();

    const promotedTitle = promotedProject?.title || 'A competitor';
    const promotedBidder = promotedProject?.handle ? `@${promotedProject.handle}` : 'A challenger';
    const amountFormatted = `$${(amountMinor / 100).toFixed(0)}`;

    // 2. Fetch displaced board events generated by this payment
    const { data: events, error: eventsError } = await supabaseAdmin
      .from('board_events')
      .select('project_id, previous_rank, new_rank, event_type')
      .eq('payment_id', paymentId);

    if (eventsError || !events || events.length === 0) {
      return;
    }

    // Filter events for projects other than the promoted one that dropped in rank
    const displacedEvents = events.filter(
      (e) =>
        e.project_id &&
        e.project_id !== promotedProjectId &&
        (e.event_type === 'left_top_100' || (e.previous_rank && e.new_rank && e.new_rank > e.previous_rank))
    );

    if (displacedEvents.length === 0) {
      return;
    }

    for (const evt of displacedEvents) {
      try {
        // Find project and its owner
        const { data: project } = await supabaseAdmin
          .from('projects')
          .select('id, title, user_id')
          .eq('id', evt.project_id)
          .maybeSingle();

        if (!project || !project.user_id) continue;

        // Fetch owner alert preferences
        const { data: userProfile } = await supabaseAdmin
          .from('users')
          .select('id, alert_preferences')
          .eq('id', project.user_id)
          .maybeSingle();

        const prefs: AlertPreferences = (userProfile?.alert_preferences as AlertPreferences) || {};
        // Default to true if not explicitly opted out
        if (prefs.emailAlerts === false) {
          continue;
        }

        // Fetch user email from Supabase Auth
        const { data: authData, error: authError } = await supabaseAdmin.auth.admin.getUserById(project.user_id);
        if (authError || !authData?.user?.email) {
          continue;
        }

        const ownerEmail = authData.user.email;
        const prevRank = evt.previous_rank || 1;
        const targetRank = evt.new_rank || (evt.event_type === 'left_top_100' ? 101 : prevRank + 1);

        // If instantKingAlert is true and this was Rank #1 or Graveyard, always send;
        // If emailAlerts is true, send standard rank drop alert.
        await sendOutbidAlert({
          to: ownerEmail,
          projectTitle: project.title,
          previousRank: prevRank,
          newRank: targetRank,
          promotedTitle,
          promotedBidder,
          promotedAmountFormatted: amountFormatted,
          reclaimUrl: `https://bumpone.lol/?claim=true&slot=${prevRank}`,
        });
      } catch (err) {
        console.warn(`[RankAlerts] Failed to dispatch alert for project ${evt.project_id}:`, err);
      }
    }
  } catch (err) {
    console.warn('[RankAlerts] Background dispatch encountered an error:', err);
  }
}
